version: '3.8'

services:
    app:
        container_name: node-url-shortener
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
        - .env
        ports:
        - ${API_PORT}:${API_PORT}
        - 9228:9228
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
        depends_on:
        - mongo-db
        links:
        - mongo-db
        - redis

    mongo-db:
        image: mongo:latest
        container_name: mongo-db
        restart: always
        env_file:
            - .env
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_DATABASE}
            - APP_USER=${DB_USERNAME}
            - APP_PWD=${DB_PASSWORD}
            - DB_NAME=${DB_DATABASE}
        volumes:
            - dbdata-volume:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    mongoexpress:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        env_file:
            - .env
        ports:
            - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
        links:
            - mongo-db
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_NAME}:${DB_PORT}/${DB_DATABASE}
            - ME_CONFIG_BASICAUTH_USERNAME=${DB_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASSWORD}

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        env_file:
            - .env        
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning --save 20 1
            
volumes:
  dbdata-volume: