version: '3.7'

services:
  app:
    container_name: node-url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
      - 9228:9228
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - dbdata-volume:/data/db
    environment:
      MONGO_INITDB_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    networks:
      - backend

volumes:
  dbdata-volume:      