version: '3'

services:
  app:
    container_name: node-url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229