version: '3'

services:
  app:
    container_name: node-url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # environment:
    #   - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
      - 9228:9228
    networks:
      - backend